# Generated by Django 5.0.14 on 2026-04-27 19:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


def forwards_migrate_inventory_items(apps, schema_editor):
    PlayerInventory = apps.get_model("game_logic", "PlayerInventory")
    PlayerItem = apps.get_model("game_logic", "PlayerItem")
    ItemTemplate = apps.get_model("game_data", "ItemTemplate")

    for inventory in PlayerInventory.objects.all().iterator():
        if PlayerItem.objects.filter(inventory=inventory).exists():
            continue

        items = inventory.items or []
        slot_index = 0
        for item in items:
            template_id = item.get("template_id")
            quantity = item.get("quantity", 1)
            if not template_id:
                continue
            try:
                template = ItemTemplate.objects.get(id=template_id)
            except ItemTemplate.DoesNotExist:
                continue

            try:
                quantity_int = int(quantity)
            except Exception:
                quantity_int = 1
            if quantity_int < 1:
                quantity_int = 1

            PlayerItem.objects.create(
                inventory=inventory,
                item_template=template,
                quantity=quantity_int,
                slot_index=slot_index,
            )
            slot_index += 1

        inventory.slots_used = PlayerItem.objects.filter(inventory=inventory).count()
        inventory.save(update_fields=["slots_used"])


def backwards_migrate_inventory_items(apps, schema_editor):
    PlayerItem = apps.get_model("game_logic", "PlayerItem")
    PlayerItem.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('game_data', '0001_initial'),
        ('game_logic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('slot_index', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_rel', to='game_logic.playerinventory')),
                ('item_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_items', to='game_data.itemtemplate')),
            ],
            options={
                'verbose_name': 'Player Item',
                'verbose_name_plural': 'Player Items',
                'db_table': 'player_items',
                'ordering': ['slot_index'],
                'indexes': [models.Index(fields=['inventory', 'slot_index'], name='player_item_invento_4ede40_idx'), models.Index(fields=['inventory', 'item_template'], name='player_item_invento_84a0c1_idx')],
                'unique_together': {('inventory', 'slot_index')},
            },
        ),
        migrations.RunPython(forwards_migrate_inventory_items, backwards_migrate_inventory_items),
    ]
