# =========================================================
# N8N - PLATAFORMA DE AUTOMAÇÃO DE FLUXOS DE TRABALHO
# =========================================================
# Versão: 1.113.3
# Descrição: Configuração unificada do N8N com seu próprio
#            PostgreSQL e Redis dedicados.
# =========================================================

services:
  # =========================================================
  # SERVIÇO: N8N UNIFICADO
  # =========================================================
  # Serviço único do N8N com interface web, webhooks e workers
  # Configurado com banco de dados e Redis próprios
  # =========================================================
  n8n:
    image: n8nio/n8n:1.113.3
    depends_on:
      - postgres_n8n
      - redis_n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - tmp_data:/home/n8n/.tmp
    networks:
      - app_network
    restart: always
    env_file:
      - .env
    environment:
      # =========================================================
      # CONFIGURAÇÃO DE BANCO DE DADOS DEDICADO
      # =========================================================
      DB_TYPE: postgresdb
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_HOST: postgres_n8n
      DB_POSTGRESDB_DATABASE: n8n_fila
      DB_POSTGRESDB_USER: postgres
      DB_POSTGRESDB_PASSWORD: minha_senha_super_segura_2024!
      
      # =========================================================
      # CONFIGURAÇÃO DE SEGURANÇA E ACESSO
      # =========================================================
      N8N_ENCRYPTION_KEY: Y8Dmy5FhuRIDGIrs
      N8N_HOST: 192.168.1.74:5678
      N8N_EDITOR_BASE_URL: http://192.168.1.74:5678/
      N8N_PROTOCOL: http
      NODE_ENV: production
      WEBHOOK_URL: http://192.168.1.74:5678/
      
      # =========================================================
      # CONFIGURAÇÃO DE REDIS DEDICADO
      # =========================================================
      QUEUE_BULL_REDIS_HOST: redis_n8n
      QUEUE_BULL_REDIS_PORT: 6379
      QUEUE_BULL_REDIS_DB: 0
      
      # =========================================================
      # CONFIGURAÇÃO DE EXECUÇÃO
      # =========================================================
      EXECUTIONS_MODE: regular
      NODE_FUNCTION_ALLOW_EXTERNAL: moment,lodash,moment-with-locales
      EXECUTIONS_DATA_PRUNE: 'true'
      EXECUTIONS_DATA_MAX_AGE: 336
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: 'true'
      N8N_SECURE_COOKIE: "false"

# =========================================================
# VOLUMES
# =========================================================
# Configuração de volumes para persistência de dados
# =========================================================
volumes:
  n8n_data:                               # Volume para dados do N8N
    driver: local                          # Driver local para armazenamento
  tmp_data:                               # Volume para arquivos temporários
    driver: local                          # Driver local para armazenamento

# =========================================================
# NETWORKS
# =========================================================
# Configuração de rede para comunicação entre serviços
# =========================================================
networks:
  app_network:                            # Rede compartilhada entre todos os serviços
    external: true                         # Indica que a rede é criada externamente