# Generated by Django 5.0.14 on 2026-01-19 14:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification'),
        ('entities', '0004_entity_primary_color_dark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tenant Module',
                'verbose_name_plural': 'Tenant Modules',
            },
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='core_notifi_recipie_4d7e73_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='core_notifi_recipie_aeffaf_idx',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='notification_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='link',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='read_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sender',
        ),
        migrations.AddField(
            model_name='notification',
            name='target_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='entities.entity'),
        ),
        migrations.AddField(
            model_name='tenantmodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_modules', to='core.appmodule'),
        ),
        migrations.AddField(
            model_name='tenantmodule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_modules', to='entities.entity'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantmodule',
            unique_together={('tenant', 'module')},
        ),
    ]
