global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter - System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor - Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Redis Exporter - Redis metrics
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

  # PostgreSQL Exporter - Database metrics
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Chatwoot Application
  - job_name: 'chatwoot'
    static_configs:
      - targets: ['projetoravenna-chatwoot-rails-1:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # N8N Application
  - job_name: 'n8n'
    static_configs:
      - targets: ['projetoravenna-n8n-1:5678']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Evolution API
  - job_name: 'evolution-api'
    static_configs:
      - targets: ['evolution_api:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s