# Generated by Django 5.1.4 on 2026-01-06 13:41

from django.db import migrations


def populate_search_vectors(apps, schema_editor):
    """Populate search_vector field for all existing articles"""
    from django.contrib.postgres.search import SearchVector
    
    Article = apps.get_model('articles', 'Article')
    
    # Update all articles with search vectors
    for article in Article.objects.all():
        article.search_vector = (
            SearchVector('title', weight='A', config='portuguese') +
            SearchVector('content', weight='B', config='portuguese')
        )
    
    # Bulk update for efficiency
    Article.objects.bulk_update(
        Article.objects.all(),
        ['search_vector'],
        batch_size=100
    )


def reverse_populate(apps, schema_editor):
    """Clear search vectors on reverse migration"""
    Article = apps.get_model('articles', 'Article')
    Article.objects.update(search_vector=None)


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_search_vector_article_search_vector_idx'),
    ]

    operations = [
        migrations.RunPython(populate_search_vectors, reverse_populate),
    ]
