# Generated by Django 5.2.9 on 2026-01-06 13:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_populate_search_vectors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleFavorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='articles.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article Favorite',
                'verbose_name_plural': 'Article Favorites',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['article'], name='articles_ar_article_51fcfc_idx'), models.Index(fields=['user'], name='articles_ar_user_id_f5b7f0_idx')],
                'unique_together': {('article', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ArticleLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='articles.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article Like',
                'verbose_name_plural': 'Article Likes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['article'], name='articles_ar_article_e9de36_idx'), models.Index(fields=['user'], name='articles_ar_user_id_3a5f1f_idx')],
                'unique_together': {('article', 'user')},
            },
        ),
    ]
