# Generated by Django 5.2.9 on 2026-01-06 14:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_articlefavorite_articlelike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, help_text='Session key for deduplication', max_length=255)),
                ('ip_hash', models.CharField(help_text='SHA256 hash of IP address for deduplication only', max_length=64)),
                ('user_agent', models.CharField(blank=True, help_text='Browser user agent string', max_length=500)),
                ('referer', models.URLField(blank=True, help_text='HTTP referer (where visitor came from)', max_length=500)),
                ('reading_progress', models.IntegerField(default=0, help_text='Reading progress percentage (0-100)')),
                ('time_spent', models.IntegerField(default=0, help_text='Time spent reading in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='articles.article')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article View',
                'verbose_name_plural': 'Article Views',
                'db_table': 'article_views',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, help_text='When the reading session ended', null=True)),
                ('duration_seconds', models.IntegerField(default=0, help_text='Total duration in seconds')),
                ('scrolled_to_bottom', models.BooleanField(default=False, help_text='Did the user scroll to the bottom?')),
                ('interactions', models.IntegerField(default=0, help_text='Number of interactions (clicks, likes, comments)')),
                ('article_view', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='articles.articleview')),
            ],
            options={
                'verbose_name': 'Reading Session',
                'verbose_name_plural': 'Reading Sessions',
                'db_table': 'reading_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='articleview',
            index=models.Index(fields=['article', 'created_at'], name='av_article_created_idx'),
        ),
        migrations.AddIndex(
            model_name='articleview',
            index=models.Index(fields=['session_id', 'article'], name='av_session_article_idx'),
        ),
        migrations.AddIndex(
            model_name='articleview',
            index=models.Index(fields=['user', 'created_at'], name='av_user_created_idx'),
        ),
    ]
