# Generated by Django 5.2.9 on 2026-01-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_comment_guest_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Short description shown in lists', max_length=500),
        ),
    ]
