# Generated by Django 5.0.14 on 2026-01-19 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_article_excerpt'),
        ('entities', '0004_entity_primary_color_dark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='entities.entity'),
        ),
        migrations.AddField(
            model_name='category',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='entities.entity'),
        ),
        migrations.AddField(
            model_name='tag',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='entities.entity'),
        ),
    ]
