# Generated by Django 5.0.14 on 2026-01-19 14:44

import apps.articles.models
import django.db.models.deletion
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_article_tenant_category_tenant_tag_tenant'),
        ('entities', '0004_entity_primary_color_dark_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='articlefavorite',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_favorites', to='entities.entity'),
        ),
        migrations.AddField(
            model_name='articlelike',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_likes', to='entities.entity'),
        ),
        migrations.AddField(
            model_name='articleview',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_views', to='entities.entity'),
        ),
        migrations.AddField(
            model_name='comment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='entities.entity'),
        ),
        migrations.AddField(
            model_name='readingsession',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reading_sessions', to='entities.entity'),
        ),
        migrations.AlterField(
            model_name='article',
            name='banner',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=85, scale=None, size=[1200, 630], upload_to=apps.articles.models.tenant_upload_path),
        ),
        migrations.AddIndex(
            model_name='articleview',
            index=models.Index(fields=['tenant', 'created_at'], name='av_tenant_created_idx'),
        ),
    ]
