# Generated by Django 5.0.14 on 2026-01-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_articlefavorite_tenant_articlelike_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_json',
            field=models.JSONField(blank=True, default=dict, help_text='Structured block content (TipTap)'),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Rascunho'), ('PUBLISHED', 'Publicado'), ('ARCHIVED', 'Arquivado')], default='DRAFT', max_length=10),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, help_text='Legacy HTML content'),
        ),
    ]
