# Generated by Django 5.0.14 on 2026-04-30 00:00

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminAuditEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("action", models.CharField(choices=[("activate", "Activate"), ("deactivate", "Deactivate"), ("ban", "Ban"), ("unban", "Unban"), ("reset_password", "Reset Password"), ("change_groups", "Change Groups"), ("update_user", "Update User")], db_index=True, max_length=32)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="admin_audit_actor_events", to=settings.AUTH_USER_MODEL)),
                ("target", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="admin_audit_target_events", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "accounts_admin_audit_events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="adminauditevent",
            index=models.Index(fields=["target", "-created_at"], name="accounts_ad_target__8f2eb8_idx"),
        ),
        migrations.AddIndex(
            model_name="adminauditevent",
            index=models.Index(fields=["actor", "-created_at"], name="accounts_ad_actor__2d6bd1_idx"),
        ),
        migrations.AddIndex(
            model_name="adminauditevent",
            index=models.Index(fields=["action", "-created_at"], name="accounts_ad_action__bbd7f7_idx"),
        ),
    ]

