# Generated by Django 5.2.9 on 2026-01-05 19:50

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='WEBP', help_text='User profile picture (will be resized to 400x400 WEBP)', keep_meta=True, null=True, quality=90, scale=None, size=[400, 400], upload_to='avatars/'),
        ),
    ]
