# Generated by Django 5.0.14 on 2026-04-30 04:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_adminauditevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOneTimeCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('purpose', models.CharField(choices=[('email_verify', 'Email Verify'), ('password_reset', 'Password Reset')], db_index=True, max_length=32)),
                ('code_hash', models.CharField(max_length=255)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'accounts_email_one_time_codes',
            },
        ),
        migrations.CreateModel(
            name='SMTPSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('port', models.PositiveIntegerField(default=587)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password_encrypted', models.TextField(blank=True)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('timeout', models.PositiveIntegerField(default=10)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=255)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'db_table': 'accounts_smtp_settings',
            },
        ),
        migrations.RenameIndex(
            model_name='adminauditevent',
            new_name='accounts_ad_target__c5500a_idx',
            old_name='accounts_ad_target__8f2eb8_idx',
        ),
        migrations.RenameIndex(
            model_name='adminauditevent',
            new_name='accounts_ad_actor_i_f01265_idx',
            old_name='accounts_ad_actor__2d6bd1_idx',
        ),
        migrations.RenameIndex(
            model_name='adminauditevent',
            new_name='accounts_ad_action_236f8e_idx',
            old_name='accounts_ad_action__bbd7f7_idx',
        ),
        migrations.AlterField(
            model_name='adminauditevent',
            name='action',
            field=models.CharField(choices=[('create_user', 'Create User'), ('register_user', 'Register User'), ('activate', 'Activate'), ('deactivate', 'Deactivate'), ('ban', 'Ban'), ('unban', 'Unban'), ('reset_password', 'Reset Password'), ('change_groups', 'Change Groups'), ('update_user', 'Update User')], db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='emailonetimecode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_time_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='emailonetimecode',
            index=models.Index(fields=['user', 'purpose', '-created_at'], name='accounts_em_user_id_32418c_idx'),
        ),
        migrations.AddIndex(
            model_name='emailonetimecode',
            index=models.Index(fields=['purpose', 'expires_at'], name='accounts_em_purpose_f134e8_idx'),
        ),
    ]
