# Generated by Django 5.2.9 on 2026-01-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Short biography for the user profile.', verbose_name='biography'),
        ),
    ]
