# Generated by Django 5.0.14 on 2026-04-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailonetimecode_smtpsettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminauditevent',
            name='action',
            field=models.CharField(choices=[('create_user', 'Create User'), ('register_user', 'Register User'), ('email_verify_sent', 'Email Verify Sent'), ('email_verified', 'Email Verified'), ('password_reset_sent', 'Password Reset Sent'), ('password_reset_confirmed', 'Password Reset Confirmed'), ('activate', 'Activate'), ('deactivate', 'Deactivate'), ('ban', 'Ban'), ('unban', 'Unban'), ('reset_password', 'Reset Password'), ('change_groups', 'Change Groups'), ('update_user', 'Update User')], db_index=True, max_length=32),
        ),
    ]
