# Generated by Django 5.0.14 on 2026-01-19 14:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_bio'),
        ('entities', '0004_entity_primary_color_dark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('EDITOR', 'Editor'), ('MEMBER', 'Member')], default='MEMBER', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='entities.entity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant Membership',
                'verbose_name_plural': 'Tenant Memberships',
                'unique_together': {('user', 'tenant')},
            },
        ),
    ]
