# Generated by Django 5.0.14 on 2026-04-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_adminauditevent_action'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='emailonetimecode',
            index=models.Index(fields=['ip_address', 'purpose', '-created_at'], name='accounts_em_ip_addr_c65324_idx'),
        ),
    ]
