# Generated by Django 6.0 on 2026-01-20 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tenantmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='primary_color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #FFFFFF or #FFF)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Cor Primária Personalizada'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='primary_color_dark',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #FFFFFF or #FFF)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Cor Primária Personalizada (Dark)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #FFFFFF or #FFF)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Cor Secundária Personalizada'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='secondary_color_dark',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #FFFFFF or #FFF)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Cor Secundária Personalizada (Dark)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Claro'), ('dark', 'Escuro'), ('system', 'Sistema')], default='system', max_length=10, verbose_name='Preferência de Tema'),
        ),
    ]
