# Generated by Django 5.0.14 on 2026-04-27 19:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('map_key', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('min_level', models.IntegerField(default=1)),
                ('max_level', models.IntegerField(default=100)),
                ('max_players', models.IntegerField(default=50)),
                ('environment', models.CharField(blank=True, max_length=100)),
                ('spawn_points', models.JSONField(default=list)),
                ('npcs', models.JSONField(default=list)),
                ('monsters', models.JSONField(default=list)),
                ('resources', models.JSONField(default=list)),
                ('is_pvp_enabled', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Map',
                'verbose_name_plural': 'Maps',
                'db_table': 'map_data',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('item_type', models.CharField(max_length=50)),
                ('rarity', models.CharField(default='common', max_length=20)),
                ('base_damage', models.IntegerField(default=0)),
                ('base_defense', models.IntegerField(default=0)),
                ('base_health', models.IntegerField(default=0)),
                ('base_mana', models.IntegerField(default=0)),
                ('icon_path', models.CharField(blank=True, max_length=255)),
                ('model_path', models.CharField(blank=True, max_length=255)),
                ('stack_size', models.IntegerField(default=1)),
                ('is_droppable', models.BooleanField(default=True)),
                ('is_tradable', models.BooleanField(default=True)),
                ('price', models.IntegerField(default=0)),
                ('level_required', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item Template',
                'verbose_name_plural': 'Item Templates',
                'db_table': 'item_templates',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['item_type', 'rarity'], name='item_templa_item_ty_069aad_idx'), models.Index(fields=['level_required'], name='item_templa_level_r_cf1646_idx')],
            },
        ),
        migrations.CreateModel(
            name='SkillTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('skill_type', models.CharField(max_length=50)),
                ('damage', models.IntegerField(default=0)),
                ('healing', models.IntegerField(default=0)),
                ('mana_cost', models.IntegerField(default=0)),
                ('cooldown', models.FloatField(default=0.0)),
                ('range', models.FloatField(default=0.0)),
                ('cast_time', models.FloatField(default=0.0)),
                ('icon_path', models.CharField(blank=True, max_length=255)),
                ('animation_path', models.CharField(blank=True, max_length=255)),
                ('level_required', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skill Template',
                'verbose_name_plural': 'Skill Templates',
                'db_table': 'skill_templates',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['skill_type'], name='skill_templ_skill_t_2dbdfa_idx'), models.Index(fields=['level_required'], name='skill_templ_level_r_46914c_idx')],
            },
        ),
    ]
