# Generated by Django 5.2.9 on 2026-01-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='brand_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Marca'),
        ),
        migrations.AddField(
            model_name='entity',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Domínio/Subdomínio'),
        ),
        migrations.AddField(
            model_name='entity',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='tenants/favicons/'),
        ),
        migrations.AddField(
            model_name='entity',
            name='footer_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='entity',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tenants/logos/'),
        ),
        migrations.AddField(
            model_name='entity',
            name='primary_color',
            field=models.CharField(default='#44B78B', max_length=7, verbose_name='Cor Primária'),
        ),
        migrations.AddField(
            model_name='entity',
            name='secondary_color',
            field=models.CharField(default='#2D3748', max_length=7, verbose_name='Cor Secundária'),
        ),
        migrations.AddField(
            model_name='entity',
            name='social_links',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
