# Generated by Django 5.2.9 on 2026-01-13 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_entity_brand_name_entity_domain_entity_favicon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='primary_color',
            field=models.CharField(default='#44B78B', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #FFFFFF or #FFF)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Cor Primária'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='secondary_color',
            field=models.CharField(default='#2D3748', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #FFFFFF or #FFF)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Cor Secundária'),
        ),
    ]
