# Generated by Django 5.2.9 on 2026-01-13 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_alter_entity_primary_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='primary_color_dark',
            field=models.CharField(default='#44B78B', help_text='Cor primária para dark mode (opcional)', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #FFFFFF or #FFF)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Cor Primária (Dark Mode)'),
        ),
        migrations.AddField(
            model_name='entity',
            name='secondary_color_dark',
            field=models.CharField(default='#0C4B33', help_text='Cor secundária para dark mode (opcional)', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #FFFFFF or #FFF)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Cor Secundária (Dark Mode)'),
        ),
    ]
