# Generated by Django 5.0.14 on 2026-01-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_entity_primary_color_dark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='default_theme',
            field=models.CharField(choices=[('light', 'Claro'), ('dark', 'Escuro')], default='light', max_length=5, verbose_name='Tema Padrão'),
        ),
    ]
