# Generated by Django 5.0.14 on 2026-01-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_entity_default_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='email_from_address',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email From Address'),
        ),
        migrations.AddField(
            model_name='entity',
            name='email_from_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email From Name'),
        ),
        migrations.AddField(
            model_name='entity',
            name='smtp_host',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SMTP Host'),
        ),
        migrations.AddField(
            model_name='entity',
            name='smtp_password',
            field=models.CharField(blank=True, help_text='Will be stored as plain text for now, consider encryption later.', max_length=255, null=True, verbose_name='SMTP Password'),
        ),
        migrations.AddField(
            model_name='entity',
            name='smtp_port',
            field=models.IntegerField(blank=True, null=True, verbose_name='SMTP Port'),
        ),
        migrations.AddField(
            model_name='entity',
            name='smtp_use_tls',
            field=models.BooleanField(default=True, verbose_name='Use TLS'),
        ),
        migrations.AddField(
            model_name='entity',
            name='smtp_user',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SMTP User'),
        ),
    ]
