# Generated by Django 5.0.14 on 2026-01-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_entity_email_from_address_entity_email_from_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='default_language',
            field=models.CharField(choices=[('pt-br', 'Português (Brasil)'), ('en', 'English'), ('es', 'Español')], default='pt-br', max_length=10, verbose_name='Idioma Padrão'),
        ),
    ]
