# Generated by Django 5.0.14 on 2026-01-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0007_entity_default_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
    ]
