# Generated by Django 6.0 on 2026-01-20 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0008_entity_onboarding_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='default_theme',
        ),
    ]
