# Generated by Django 5.0.14 on 2026-04-27 19:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic_count', models.IntegerField(default=0)),
                ('reply_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Forum Category',
                'verbose_name_plural': 'Forum Categories',
                'db_table': 'forum_categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('archived', 'Archived')], default='open', max_length=20)),
                ('reply_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('last_reply_at', models.DateTimeField(blank=True, null=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_topics', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='forum.forumcategory')),
                ('last_reply_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_replies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'db_table': 'forum_topics',
                'ordering': ['-is_pinned', '-last_reply_at'],
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_solution', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('hidden_reason', models.TextField(blank=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_replies', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forum.topic')),
            ],
            options={
                'verbose_name': 'Reply',
                'verbose_name_plural': 'Replies',
                'db_table': 'forum_replies',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reaction', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('heart', 'Heart'), ('laugh', 'Laugh'), ('wow', 'Wow')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='forum.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'forum_topic_reactions',
            },
        ),
        migrations.CreateModel(
            name='ReplyReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reaction', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('heart', 'Heart'), ('laugh', 'Laugh'), ('wow', 'Wow')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='forum.reply')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'forum_reply_reactions',
                'unique_together': {('user', 'reply', 'reaction')},
            },
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['-last_reply_at'], name='forum_topic_last_re_cc55ce_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['slug'], name='forum_topic_slug_8d02e5_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['-reply_count'], name='forum_topic_reply_c_182bda_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['status', '-last_reply_at'], name='forum_topic_status_adfd1d_idx'),
        ),
        migrations.AddIndex(
            model_name='reply',
            index=models.Index(fields=['topic', 'created_at'], name='forum_repli_topic_i_c1c220_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='topicreaction',
            unique_together={('user', 'topic', 'reaction')},
        ),
    ]
