# =========================================================
# MINIO - ARMAZENAMENTO DE OBJETOS COMPATÍVEL COM S3
# =========================================================
# Versão: RELEASE.2025-09-07T16-13-09Z
# Descrição: Configuração do serviço MinIO para armazenamento
#            de arquivos, mídias e objetos compatível com S3.
# =========================================================

services:
  # =========================================================
  # SERVIÇO: MINIO
  # =========================================================
  # Armazenamento de objetos S3-compatível para arquivos e mídias
  # Utilizado por Chatwoot e Evolution API para armazenar anexos
  # =========================================================
  minio:
    image: ${MINIO_IMAGE}                   # Imagem oficial MinIO
    command: ${MINIO_COMMAND}               # Comando para iniciar o servidor MinIO
    container_name: ${CONTAINER_NAME}       # Nome do contêiner
    networks:
      - app_network                         # Conexão com a rede compartilhada
    volumes:
      - minio_data:/data                    # Volume para persistência dos dados
    ports:
      - "9000:9000"                        # Porta da API MinIO
      - "9001:9001"                        # Porta do Console MinIO
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}  # Usuário administrador
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}  # Senha do administrador
      - MINIO_BROWSER_REDIRECT_URL=${MINIO_BROWSER_REDIRECT_URL}  # URL de redirecionamento do console
      - MINIO_SERVER_URL=${MINIO_SERVER_URL}  # URL do servidor MinIO
    restart: ${RESTART_POLICY}             # Reinicia automaticamente em caso de falha

# =========================================================
# VOLUMES
# =========================================================
# Configuração de volumes para persistência de dados
# =========================================================
volumes:
  minio_data:                               # Volume para dados do MinIO
    driver: local                          # Driver local para armazenamento

# =========================================================
# NETWORKS
# =========================================================
# Configuração de rede para comunicação entre serviços
# =========================================================
networks:
  app_network:                             # Rede compartilhada entre todos os serviços
    external: true                         # Indica que a rede é criada externamente