version: '3.8'

services:
  # === Postgres para o Chatwoot ===
  postgres:
    image: pgvector/pgvector:pg16
    container_name: chatwoot-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - chatwoot-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME} -d ${POSTGRES_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ravenna_net

  # === Redis para cache do Chatwoot ===
  redis:
    image: redis:7
    container_name: chatwoot-redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - chatwoot-redis-data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD} ping || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ravenna_net

  # === Chatwoot Rails ===
  rails:
    image: chatwoot/chatwoot:latest
    container_name: chatwoot-rails
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file: .env-chatwoot
    ports:
      - "3666:3000"
    networks:
      - ravenna_net
      - minio_net
    command: >
      sh -c "
      bundle exec rails db:chatwoot_prepare &&
      bundle exec rails s -b 0.0.0.0 -p 3000
      "

  # === Sidekiq (jobs em background) ===
  sidekiq:
    image: chatwoot/chatwoot:latest
    container_name: chatwoot-sidekiq
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file: .env-chatwoot
    networks:
      - ravenna_net
      - minio_net
    command: bundle exec sidekiq -C config/sidekiq.yml

volumes:
  chatwoot-postgres-data:
  chatwoot-redis-data:

networks:
  ravenna_net:
    external: true
  minio_net:
    external: true