# =========================================================
# POSTGRESQL - PROJETO RAVENNA
# =========================================================
# Descrição: Configuração dos bancos de dados PostgreSQL v16
#            específicos para cada serviço do Projeto Ravenna
# =========================================================

services:
  postgres_chatwoot:
    image: postgres:16-alpine
    container_name: postgres_chatwoot
    restart: ${RESTART_POLICY}
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: chatwoot_production
    volumes:
      - postgres_chatwoot_data:/var/lib/postgresql/data
    networks:
      - app_network
    ports:
      - "${HOST_IP}:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres_n8n:
    image: postgres:16-alpine
    container_name: postgres_n8n
    restart: ${RESTART_POLICY}
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: n8n_production
    volumes:
      - postgres_n8n_data:/var/lib/postgresql/data
    networks:
      - app_network
    ports:
      - "${HOST_IP}:5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres_evolution:
    image: postgres:16-alpine
    container_name: postgres_evolution
    restart: ${RESTART_POLICY}
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: evolution_production
    volumes:
      - postgres_evolution_data:/var/lib/postgresql/data
    networks:
      - app_network
    ports:
      - "${HOST_IP}:5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_chatwoot_data:
    driver: local
  postgres_n8n_data:
    driver: local
  postgres_evolution_data:
    driver: local