# =========================================================
# REDIS - PROJETO RAVENNA
# =========================================================
# Descrição: Configuração do Redis v8.2 para cache e filas
#            do Projeto Ravenna
# =========================================================

version: '3.8'

services:
  redis_chatwoot:
    image: redis:8.2-alpine
    container_name: redis_chatwoot
    restart: ${RESTART_POLICY}
    env_file:
      - .env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_chatwoot_data:/data
    networks:
      - app_network
    ports:
      - "${HOST_IP}:6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis_evolution:
    image: redis:8.2-alpine
    container_name: redis_evolution
    restart: ${RESTART_POLICY}
    env_file:
      - .env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_evolution_data:/data
    networks:
      - app_network
    ports:
      - "${HOST_IP}:6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis_n8n:
    image: redis:8.2-alpine
    container_name: redis_n8n
    restart: ${RESTART_POLICY}
    env_file:
      - .env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_n8n_data:/data
    networks:
      - app_network
    ports:
      - "${HOST_IP}:6381:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  redis_chatwoot_data:
    driver: local
  redis_evolution_data:
    driver: local
  redis_n8n_data:
    driver: local